#!/usr/bin/env bash
SCRIPT=stratum
mkdir /stratum 2>/dev/null
export PATH=$PATH:/stratum
touch /var/log/stratum.log; chmod 666 /var/log/stratum.log
LOGFILE=/var/log/stratum.log
BACKUP=/var/backups/stratum
mkdir $BACKUP 2>/dev/null

echo -e "\e[32m $(date +%F' '%T) $SCRIPT - Start script ...\e[0m" >> $LOGFILE

check_distro () {
lsb_release -d | logline
uname -a | logline
}

logline() {
    while IFS= read -r line; do
        echo "$(date +%F' '%T) $SCRIPT - $line"
        echo "$(date +%F' '%T) $SCRIPT - $line" >> $LOGFILE
    done
}

install_stuff_1() {
  echo -e "\e[42m \e[0m\e[92m install_stuff_1: screen ntpdate unzip lsb-release ...\e[0m" | logline
  apt -y install screen | logline
  /usr/bin/screen -dmS stratum-watchdog '' &
  apt -y install ntpdate unzip lsb-release
  ntpdate -s time.nist.gov | logline
  date | logline
}

root_check () {
if [ "$USER" != "root" ];then
		echo -e "\e[31mRun this script as root! exit...\e[0m"
		echo "Run this script as root! exit..." | logline; exit
	else
		echo -e "\e[32mStart OK ...\e[0m" | logline
fi
}

create_busyuser () {
busyuser=busyman
groupadd $busyuser
useradd $busyuser -s /bin/bash -m -g $busyuser
# allow execute crontab for busyuser
cat > /etc/cron.allow << EOF
$busyuser
EOF
EOF 2>/dev/null # without this line code colors in Atom editor are crazy

echo -e "\e[104m \e[0m\e[94m user busyman created ...\e[0m" | logline
cat /etc/cron.allow
}

rm_files () {
  if [ -z $./var/backups/dpkg*.gz ];then
  	rm /var/backups/dpkg*.gz
  fi
  if [ -z $./var/cache/apt/*.bin ];then
  	rm /var/cache/apt/*.bin
  fi
  if [ -z $./var/cache/debconf/* ];then
  	rm /var/cache/debconf/*
  fi
  if [ -z $./var/cache/apt/archives/*.deb ];then
  	rm /var/cache/apt/archives/*.deb
  fi
  if [ -z $./var/lib/apt/lists/*.* ];then
  	rm /var/lib/apt/lists/*.*
  fi
  if [ -z $./etc/apt/apt.conf ];then
  	rm /etc/apt/apt.conf
  fi
}

apt_files () {
echo -e "\e[35m create /etc/apt/apt.conf and add Debian Jessie main repo ... \e[0m"
echo 'APT::Install-Recommends "false" ; APT::Install-Suggests "false" ;' >> /etc/apt/apt.conf
rm /etc/apt/sources.list
echo 'deb http://ftp.debian.org/debian jessie main' >> /etc/apt/sources.list
apt-get update && apt-get clean
}

install_ssh () {
  apt-get -qq install -f --no-install-recommends openssh-server | logline
  echo -e "\e[93m #allow root ssh login,, sed -i 's/without-password/yes/g' /etc/ssh/sshd_config \e[0m" | logline
  sleep 1
  sed -i 's/without-password/yes/g' /etc/ssh/sshd_config
  echo -e "\e[34m service sshd reload && service sshd status ... \e[0m" | logline
  service sshd reload | logline
  service sshd status | logline
}

clean_apt () {
  echo -e "\e[35m apt-get --purge autoremove && apt-get clean..................\e[0m" | logline
  apt-get -qq --purge autoremove && apt-get clean
}

download_source_from_github () {
cd /tmp
wget -nv -O /tmp/master.zip --no-check-certificate https://github.com/StratumOS/StratumOS/archive/master.zip
unzip -o ./master.zip
rm ./master.zip
cd /tmp/StratumOS-master
ls -la
}

show_info () {
  echo -e "\e[42m \e[30m  |-->\e[0m\e[32m Show info ... "
  ip addr
  echo -e "\e[35m Done ... \e[0m"
}

case $1 in
  --update|-u)
		root_check
		echo -e "\e[44m start update file: "stratum" ...\e[0m\e[31m CAUTION! update itself ...  \e[0m" | logline
		if ! wget -nv -O /stratum/stratum.new --no-check-certificate http://busy4.me/stratum; then
			echo -e "\e[101m\e[30m ERROR: there is no file "stratum" on the server or no response! check again ...\e[0m" | logline
			exit 1
		else
			rm -rf $BACKUP/stratum.bak
				echo -e '\e[32m backup copy ...\e[0m'
			cp /stratum/stratum $BACKUP/stratum.bak
				echo -e '\e[35m backup file: '$BACKUP/stratum.bak' ...just in case...\e[0m'
				echo -e '\e[32m remove existing oryginal ...\e[0m'
			rm -rf /stratum/stratum
				echo -e '\e[32m copy new one...\e[0m'
			cp /stratum/stratum.new /stratum/stratum 2>/dev/null
				echo -e '\e[32m chmod +x ...\e[0m'
			chmod +x /stratum/stratum
			echo -e $"\e[32m file: \"stratum\" updated...\e[0m" | logline
		fi
		exit 0
	;;
  --help|-h)
    echo -e '\e[32m syntax:\n\
     stratum [place:action:what] [--argument]\e[0m' | logline
  ;;
  xterm:htop)
    echo -e '\e[32m OK, execute htop in xterm terminal ... \e[0m' | logline
  ;;
  --full|--all|-0)
    check_distro
    root_check
    install_stuff_1
    create_busyuser
    rm_files
    apt_files
    install_ssh
    clean_apt
    download_source_from_github
    show_info
  ;;
  '')
    echo -e '\e[44m no arguments... exit ...\e[0m'
    echo -e '\e[32m type: stratum --help [or -h] ...\e[0m'
    exit 1
  ;;
  $1)
    $1
  ;;
esac
