#!/bin/bash
# create xmrig service

cat > /etc/init.d/xmrig << EOF
#!/bin/bash
# chkconfig 235 99 10
### BEGIN INIT INFO
# Provides: System Sixty Six 
# Required-Start:    \$local_fs \$network \$syslog
# Required-Stop:     \$local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: str-xmrig
# Description:       StratumOS str-xmrig service
### END INIT INFO
# Author: Darius Mark <darius@system66.com>

case "\$1" in
	'start')
	/usr/bin/screen -dmS xmrig '/stratumos/xmrig/xmrig' &;;
	'stop')
    echo "pkill xmrig"
	  pkill xmrig
	  screen -wipe
	  screen -ls;;
  *)
	echo "Usage: $N {start|stop|status}" >&2
	exit 1
	;;
esac
EOF

chmod +x /etc/init.d/xmrig

echo "update-rc.d xmrig defaults"
update-rc.d xmrig defaults
echo "update-rc.d xmrig enable"
update-rc.d xmrig enable
