#!/bin/bash
# chkconfig 235 99 10
### BEGIN INIT INFO
# Provides: System Sixty Six 
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: stratum-watchdog
# Description:       StratumOS stratum-watchdog service
### END INIT INFO
# Author: Darius Mark <darius@system66.com>
case "$1" in
    'start')
	/usr/bin/screen -dmS stratum-watchdog '' &
  ;;
    'stop')
    screen -S stratum-watchdog -p 0 -X quit
	echo "pkill stratum-watchdog"
	pkill stratum-watchdog
	screen -ls
  ;;
    'status')
	screen -ls
  ;;
    'restart')
	screen -ls
    pkill stratum-watchdog
    screen -S stratum-watchdog -p 0 -X quit
	/usr/bin/screen -dmS stratum-watchdog ''
    screen -ls
  ;;
    *)
    echo "Usage: N {start|stop|status|restart}" >&2
    exit 1
    ;;
esac
